"""add brand_aliases — Korean/alternate brand surface forms for search resolution

96% of public.brand_nodes carry a Latin-only `brand_name` (e.g. 'GLOWNY'),
but Korean users type the Korean market name ('글로니'). There is no
transliteration bridge ('글로니' ≠ romanize('glowny')), so a curated alias
table is the only way a Korean-language brand query can resolve to the
canonical node. brand_node_cache warms these into its Hangul key index.

Revision ID: 0034
Revises: 0033
Create Date: 2026-08-23
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0034"
down_revision: str | Sequence[str] | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOTE: `brand_id` intentionally has NO FK to public.brand_nodes.
    # brand_nodes is owned by the crawler/data pipeline, not alembic (no
    # migration creates it), so a hard FK would break `alembic upgrade` in any
    # pure-migration environment (CI, fresh DB). Referential integrity is
    # enforced logically: the warm-cache join drops aliases whose brand_id has
    # no node, and the loader only writes known ids.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.brand_aliases (
            id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand_id         bigint NOT NULL,
            alias            text   NOT NULL,
            alias_normalized text   NOT NULL,
            lang             text,
            source           text   NOT NULL DEFAULT 'manual',
            confidence       text   NOT NULL DEFAULT 'high',
            approved         boolean NOT NULL DEFAULT true,
            created_at       timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT brand_aliases_confidence_chk CHECK (confidence IN ('high', 'low')),
            CONSTRAINT brand_aliases_brand_alias_uq UNIQUE (brand_id, alias_normalized)
        )
        """
    )
    # Warm query filters on approved + confidence and joins by brand_id; the
    # unique constraint already indexes (brand_id, alias_normalized). Add a
    # standalone alias_normalized index for any candidate-side probe.
    op.execute("CREATE INDEX IF NOT EXISTS idx_brand_aliases_normalized ON public.brand_aliases (alias_normalized)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS public.brand_aliases")
