"""골든셋 문형 × 값 매트릭스 정의.

문형(패턴)별 20개 값. 각 값은:
  - ko: 앱 칩/화면에 노출될 한국어 표현 (판정 시 참고용)
  - en: 실제 임베딩에 들어갈 영어 쿼리 (FashionSigLIP은 영어 캡션 공간)
  - category: search_products_v6 family gate에 걸 canonical 토큰
    (tops/bottoms/dresses/outerwear/knitwear/shoes/sneakers/bags/... 20종)

tier 는 사전 예측일 뿐 — 최종 판정은 사람이 리포트를 보고 내린다.
  t1 = 안전 예상 (시각 속성, 임베딩이 확실히 잡을 것)
  t2 = Kiko다움 검증 대상 (무드/에스테틱 — 이번 평가의 본체)
  t3 = 대조군 (구조적으로 불리하다고 예측 — 데이터로 확인)

여성/남성 매트릭스는 문형·슬롯 구조가 동일하고 값만 다르다 (문형 단위 성적을
성별 간 비교 가능하게 유지). 남성 값은 드레스/스커트/블라우스 등 여성 전용
아이템을 배제하고 남성 카탈로그에 실재할 아이템으로 구성.
"""


def get_patterns(gender: str) -> list[dict]:
    """성별에 맞는 문형×값 매트릭스 반환. men 외에는 여성 기준(PATTERNS)."""
    return PATTERNS_MEN if gender == "men" else PATTERNS


PATTERNS: list[dict] = [
    {
        "id": "p1_color_category",
        "name_ko": "[컬러] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "버건디 가디건", "en": "burgundy cardigan", "category": "knitwear"},
            {"ko": "카키 셔츠", "en": "khaki shirt", "category": "tops"},
            {"ko": "네이비 블레이저", "en": "navy blazer", "category": "outerwear"},
            {"ko": "베이지 트렌치코트", "en": "beige trench coat", "category": "outerwear"},
            {"ko": "블랙 슬립 드레스", "en": "black slip dress", "category": "dresses"},
            {"ko": "흰색 스니커즈", "en": "white sneakers", "category": "sneakers"},
            {"ko": "차콜 슬랙스", "en": "charcoal slacks", "category": "bottoms"},
            {"ko": "브라운 로퍼", "en": "brown loafers", "category": "shoes"},
            {"ko": "올리브 카고 팬츠", "en": "olive cargo pants", "category": "bottoms"},
            {"ko": "아이보리 블라우스", "en": "ivory blouse", "category": "tops"},
            {"ko": "레드 니트 베스트", "en": "red knit vest", "category": "knitwear"},
            {"ko": "연청 데님 자켓", "en": "light blue denim jacket", "category": "outerwear"},
            {"ko": "라벤더 후드티", "en": "lavender hoodie", "category": "tops"},
            {"ko": "머스터드 스웨터", "en": "mustard sweater", "category": "knitwear"},
            {"ko": "그레이 트라우저", "en": "grey trousers", "category": "bottoms"},
            {"ko": "핑크 미디 스커트", "en": "pink midi skirt", "category": "bottoms"},
            {"ko": "실버 미니백", "en": "silver mini bag", "category": "bags"},
            {"ko": "다크그린 코트", "en": "dark green coat", "category": "outerwear"},
            {"ko": "오렌지 티셔츠", "en": "orange t-shirt", "category": "tops"},
            {"ko": "딥퍼플 원피스", "en": "deep purple dress", "category": "dresses"},
        ],
    },
    {
        "id": "p2_material_category",
        "name_ko": "[소재] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "레더 자켓", "en": "leather jacket", "category": "outerwear"},
            {"ko": "울 코트", "en": "wool coat", "category": "outerwear"},
            {"ko": "코듀로이 팬츠", "en": "corduroy pants", "category": "bottoms"},
            {"ko": "데님 스커트", "en": "denim skirt", "category": "bottoms"},
            {"ko": "캐시미어 니트", "en": "cashmere knit sweater", "category": "knitwear"},
            {"ko": "린넨 셔츠", "en": "linen shirt", "category": "tops"},
            {"ko": "스웨이드 부츠", "en": "suede boots", "category": "shoes"},
            {"ko": "트위드 자켓", "en": "tweed jacket", "category": "outerwear"},
            {"ko": "벨벳 드레스", "en": "velvet dress", "category": "dresses"},
            {"ko": "새틴 스커트", "en": "satin skirt", "category": "bottoms"},
            {"ko": "모헤어 가디건", "en": "mohair cardigan", "category": "knitwear"},
            {"ko": "코튼 후드집업", "en": "cotton zip-up hoodie", "category": "tops"},
            {"ko": "실크 블라우스", "en": "silk blouse", "category": "tops"},
            {"ko": "나일론 바람막이", "en": "nylon windbreaker", "category": "outerwear"},
            {"ko": "무스탕 자켓", "en": "shearling jacket", "category": "outerwear"},
            {"ko": "골지 니트 탑", "en": "ribbed knit top", "category": "tops"},
            {"ko": "메시 탑", "en": "mesh top", "category": "tops"},
            {"ko": "캔버스 토트백", "en": "canvas tote bag", "category": "bags"},
            {"ko": "플리스 집업", "en": "fleece zip-up jacket", "category": "outerwear"},
            {"ko": "니트 폴로", "en": "knit polo shirt", "category": "knitwear"},
        ],
    },
    {
        "id": "p3_fit_category",
        "name_ko": "[핏/실루엣] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "오버사이즈 셔츠", "en": "oversized shirt", "category": "tops"},
            {"ko": "크롭 자켓", "en": "cropped jacket", "category": "outerwear"},
            {"ko": "와이드 팬츠", "en": "wide-leg pants", "category": "bottoms"},
            {"ko": "슬림 터틀넥", "en": "slim fit turtleneck", "category": "knitwear"},
            {"ko": "박시한 티셔츠", "en": "boxy t-shirt", "category": "tops"},
            {"ko": "A라인 스커트", "en": "a-line skirt", "category": "bottoms"},
            {"ko": "스트레이트 진", "en": "straight leg jeans", "category": "bottoms"},
            {"ko": "릴렉스핏 블레이저", "en": "relaxed fit blazer", "category": "outerwear"},
            {"ko": "핏된 원피스", "en": "fitted bodycon dress", "category": "dresses"},
            {"ko": "배기 카고 팬츠", "en": "baggy cargo pants", "category": "bottoms"},
            {"ko": "하이웨이스트 슬랙스", "en": "high-waisted trousers", "category": "bottoms"},
            {"ko": "로우라이즈 진", "en": "low-rise jeans", "category": "bottoms"},
            {"ko": "롱 코트", "en": "longline coat", "category": "outerwear"},
            {"ko": "크롭 가디건", "en": "cropped cardigan", "category": "knitwear"},
            {"ko": "플레어 팬츠", "en": "flared pants", "category": "bottoms"},
            {"ko": "플리츠 미디 스커트", "en": "pleated midi skirt", "category": "bottoms"},
            {"ko": "벌룬 소매 블라우스", "en": "balloon sleeve blouse", "category": "tops"},
            {"ko": "드롭숄더 맨투맨", "en": "drop shoulder sweatshirt", "category": "tops"},
            {"ko": "테이퍼드 슬랙스", "en": "tapered slacks", "category": "bottoms"},
            {"ko": "맥시 드레스", "en": "maxi dress", "category": "dresses"},
        ],
    },
    {
        "id": "p4_mood_category",
        "name_ko": "[무드] + [카테고리]",
        "tier": "t2",
        "values": [
            {"ko": "그런지한 니트", "en": "grunge knit sweater", "category": "knitwear"},
            {"ko": "로맨틱한 원피스", "en": "romantic dress", "category": "dresses"},
            {"ko": "미니멀한 코트", "en": "minimal coat", "category": "outerwear"},
            {"ko": "빈티지 데님 자켓", "en": "vintage denim jacket", "category": "outerwear"},
            {"ko": "레트로 맨투맨", "en": "retro sweatshirt", "category": "tops"},
            {"ko": "프레피 가디건", "en": "preppy cardigan", "category": "knitwear"},
            {"ko": "엣지있는 레더 자켓", "en": "edgy leather jacket", "category": "outerwear"},
            {"ko": "페미닌 블라우스", "en": "feminine blouse", "category": "tops"},
            {"ko": "보이시한 셔츠", "en": "boyish oversized shirt", "category": "tops"},
            {"ko": "시크한 블랙 드레스", "en": "chic black dress", "category": "dresses"},
            {"ko": "포근한 니트", "en": "cozy knit sweater", "category": "knitwear"},
            {"ko": "스포티한 바람막이", "en": "sporty windbreaker", "category": "outerwear"},
            {"ko": "우아한 미디 스커트", "en": "elegant midi skirt", "category": "bottoms"},
            {"ko": "스트릿 후드티", "en": "streetwear hoodie", "category": "tops"},
            {"ko": "보헤미안 맥시 드레스", "en": "bohemian maxi dress", "category": "dresses"},
            {"ko": "펑크 부츠", "en": "punk boots", "category": "shoes"},
            {"ko": "클래식 트렌치코트", "en": "classic trench coat", "category": "outerwear"},
            {"ko": "모던한 블레이저", "en": "modern tailored blazer", "category": "outerwear"},
            {"ko": "유니크한 미니백", "en": "quirky unique mini bag", "category": "bags"},
            {"ko": "유틸리티 자켓", "en": "utility jacket", "category": "outerwear"},
        ],
    },
    {
        "id": "p5_aesthetic",
        "name_ko": "[에스테틱/씬 키워드] + [아이템]",
        "tier": "t2",
        "values": [
            {"ko": "Y2K 탑", "en": "y2k top", "category": "tops"},
            {"ko": "고프코어 자켓", "en": "gorpcore jacket", "category": "outerwear"},
            {"ko": "다크아카데미아 블레이저", "en": "dark academia blazer", "category": "outerwear"},
            {"ko": "코케트 블라우스", "en": "coquette blouse", "category": "tops"},
            {"ko": "발레코어 스커트", "en": "balletcore skirt", "category": "bottoms"},
            {"ko": "시티보이 팬츠", "en": "city boy style pants", "category": "bottoms"},
            {"ko": "놈코어 티셔츠", "en": "normcore t-shirt", "category": "tops"},
            {"ko": "코티지코어 원피스", "en": "cottagecore dress", "category": "dresses"},
            {"ko": "테크웨어 팬츠", "en": "techwear pants", "category": "bottoms"},
            {"ko": "인디슬리즈 탑", "en": "indie sleaze top", "category": "tops"},
            {"ko": "올드머니 니트", "en": "old money knit sweater", "category": "knitwear"},
            {"ko": "아방가르드 코트", "en": "avant-garde coat", "category": "outerwear"},
            {"ko": "아메카지 셔츠", "en": "amekaji japanese workwear shirt", "category": "tops"},
            {"ko": "애슬레저 레깅스", "en": "athleisure leggings", "category": "activewear"},
            {"ko": "밀리터리 자켓", "en": "military jacket", "category": "outerwear"},
            {"ko": "웨스턴 부츠", "en": "western boots", "category": "shoes"},
            {"ko": "모드룩 원피스", "en": "1960s mod dress", "category": "dresses"},
            {"ko": "파리지앵 시크 블라우스", "en": "parisian chic blouse", "category": "tops"},
            {"ko": "그런지 플란넬 셔츠", "en": "grunge flannel shirt", "category": "tops"},
            {"ko": "K-인디 밴드 티", "en": "indie band graphic tee", "category": "tops"},
        ],
    },
    {
        "id": "p6_pattern_detail",
        "name_ko": "[패턴/디테일] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "스트라이프 셔츠", "en": "striped shirt", "category": "tops"},
            {"ko": "체크 자켓", "en": "checked jacket", "category": "outerwear"},
            {"ko": "케이블 니트", "en": "cable knit sweater", "category": "knitwear"},
            {"ko": "아가일 베스트", "en": "argyle knit vest", "category": "knitwear"},
            {"ko": "플로럴 원피스", "en": "floral print dress", "category": "dresses"},
            {"ko": "도트 블라우스", "en": "polka dot blouse", "category": "tops"},
            {"ko": "하운드투스 코트", "en": "houndstooth coat", "category": "outerwear"},
            {"ko": "레오파드 스커트", "en": "leopard print skirt", "category": "bottoms"},
            {"ko": "타탄체크 스커트", "en": "plaid tartan skirt", "category": "bottoms"},
            {"ko": "그래픽 티셔츠", "en": "graphic print t-shirt", "category": "tops"},
            {"ko": "자수 셔츠", "en": "embroidered shirt", "category": "tops"},
            {"ko": "퀼팅 자켓", "en": "quilted jacket", "category": "outerwear"},
            {"ko": "프린지 백", "en": "fringe bag", "category": "bags"},
            {"ko": "러플 블라우스", "en": "ruffle blouse", "category": "tops"},
            {"ko": "레이스 탑", "en": "lace top", "category": "tops"},
            {"ko": "핀스트라이프 슬랙스", "en": "pinstripe trousers", "category": "bottoms"},
            {"ko": "타이다이 티셔츠", "en": "tie-dye t-shirt", "category": "tops"},
            {"ko": "컬러블록 니트", "en": "colorblock knit sweater", "category": "knitwear"},
            {"ko": "카고 포켓 팬츠", "en": "cargo pocket pants", "category": "bottoms"},
            {"ko": "컷아웃 드레스", "en": "cutout dress", "category": "dresses"},
        ],
    },
    {
        "id": "p7_occasion",
        "name_ko": "[상황/TPO] + [아이템] — 대조군",
        "tier": "t3",
        "values": [
            {"ko": "소개팅 원피스", "en": "first date dress", "category": "dresses"},
            {"ko": "출근용 블레이저", "en": "office workwear blazer", "category": "outerwear"},
            {"ko": "하객룩 원피스", "en": "wedding guest dress", "category": "dresses"},
            {"ko": "휴양지 셔츠", "en": "vacation resort shirt", "category": "tops"},
            {"ko": "페스티벌 탑", "en": "music festival top", "category": "tops"},
            {"ko": "면접용 슬랙스", "en": "job interview trousers", "category": "bottoms"},
            {"ko": "데일리 니트", "en": "everyday casual knit", "category": "knitwear"},
            {"ko": "여행용 백", "en": "travel bag", "category": "bags"},
            {"ko": "운동할 때 입을 탑", "en": "workout top", "category": "activewear"},
            {"ko": "집에서 입는 라운지웨어", "en": "loungewear set", "category": "tops"},
            {"ko": "졸업식 자켓", "en": "graduation ceremony jacket", "category": "outerwear"},
            {"ko": "캠핑 자켓", "en": "camping outdoor jacket", "category": "outerwear"},
            {"ko": "클럽 파티 탑", "en": "party night out top", "category": "tops"},
            {"ko": "장마철 아우터", "en": "rainy season outer jacket", "category": "outerwear"},
            {"ko": "한여름 원피스", "en": "hot summer breezy dress", "category": "dresses"},
            {"ko": "한겨울 코트", "en": "warm winter coat", "category": "outerwear"},
            {"ko": "환절기 가디건", "en": "light layering cardigan", "category": "knitwear"},
            {"ko": "피크닉 스커트", "en": "picnic day skirt", "category": "bottoms"},
            {"ko": "공연 보러 갈 때 자켓", "en": "concert outfit jacket", "category": "outerwear"},
            {"ko": "브런치 블라우스", "en": "weekend brunch blouse", "category": "tops"},
        ],
    },
    {
        # 2026-07-15 — p_subcategory 정밀 필터 배포 전후 비교용. category 에
        # subcategory 레벨 토큰을 넣으면 (배포 후 코드에서) p_subcategory 가
        # 파생된다. target_subcategory 는 자동 hit율 계산용 정답 라벨 —
        # RPC 응답 row 의 subcategory 와 EXACT 비교.
        "id": "p8_subcategory",
        "name_ko": "[서브카테고리 정밀] — 전후 비교",
        "tier": "t1",
        "values": [
            {"ko": "흰색 스니커즈", "en": "white sneakers", "category": "sneakers", "target_subcategory": "sneakers"},
            {"ko": "블랙 부츠", "en": "black leather boots", "category": "boots", "target_subcategory": "boots"},
            {"ko": "브라운 로퍼", "en": "brown loafers", "category": "loafers", "target_subcategory": "loafers"},
            {"ko": "여름 뮬", "en": "summer mules", "category": "mules", "target_subcategory": "mules"},
            {"ko": "그레이 후드티", "en": "grey hoodie", "category": "hoodie", "target_subcategory": "hoodie"},
            {
                "ko": "네이비 맨투맨",
                "en": "navy sweatshirt",
                "category": "sweatshirt",
                "target_subcategory": "sweatshirt",
            },
            {"ko": "베이지 가디건", "en": "beige cardigan", "category": "cardigan", "target_subcategory": "cardigan"},
            {
                "ko": "블랙 터틀넥",
                "en": "black turtleneck",
                "category": "turtleneck",
                "target_subcategory": "turtleneck",
            },
            {
                "ko": "플로럴 미니 원피스",
                "en": "floral mini dress",
                "category": "mini-dress",
                "target_subcategory": "mini-dress",
            },
            {
                "ko": "새틴 미디 원피스",
                "en": "satin midi dress",
                "category": "midi-dress",
                "target_subcategory": "midi-dress",
            },
            {
                "ko": "맥시 원피스",
                "en": "flowy maxi dress",
                "category": "maxi-dress",
                "target_subcategory": "maxi-dress",
            },
            {
                "ko": "카키 카고 팬츠",
                "en": "khaki cargo pants",
                "category": "cargo-pants",
                "target_subcategory": "cargo-pants",
            },
            {
                "ko": "베이지 와이드 팬츠",
                "en": "beige wide pants",
                "category": "wide-pants",
                "target_subcategory": "wide-pants",
            },
            {"ko": "스트레이트 청바지", "en": "straight jeans", "category": "jeans", "target_subcategory": "jeans"},
            {"ko": "레더 토트백", "en": "leather tote bag", "category": "tote", "target_subcategory": "tote"},
            {"ko": "크로스바디백", "en": "crossbody bag", "category": "crossbody", "target_subcategory": "crossbody"},
            {"ko": "블랙 백팩", "en": "black backpack", "category": "backpack", "target_subcategory": "backpack"},
            {"ko": "버킷햇", "en": "bucket hat", "category": "bucket-hat", "target_subcategory": "bucket-hat"},
            {"ko": "울 비니", "en": "wool beanie", "category": "beanie", "target_subcategory": "beanie"},
            {
                "ko": "베이지 트렌치코트",
                "en": "beige trench coat",
                "category": "trench-coat",
                "target_subcategory": "trench-coat",
            },
        ],
    },
    {
        # 2026-07-15 — 순수 상황(TPO) 쿼리: 아이템 단어 없이 상황만. 봇
        # 사용자가 실제로 던지는 형태 ("결혼식 하객룩 추천해줘").
        # 2026-07-16 Phase 4a: 각 값에 `sub_queries` (LLM 확장 재현용 통제값)
        # 추가. 러너 --precision on = 멀티 확장(text_query 대표 + sub_queries
        # 인터리브 병합), off = 단일 검색(현행 baseline). 실제 봇에선 LLM 이
        # sub_queries 를 생성하지만, 하네스는 A/B 재현성을 위해 통제값 사용.
        "id": "p9_situation_pure",
        "name_ko": "[순수 상황/TPO] — Phase 4a 멀티 확장",
        "tier": "t3",
        "values": [
            {"ko": "결혼식 하객룩", "en": "elegant midi dress",
             "sub_queries": ["satin blouse", "slingback heels"], "category": None},
            {"ko": "여름 휴가룩", "en": "flowy summer maxi dress",
             "sub_queries": ["linen shirt", "straw tote bag"], "category": None},
            {"ko": "첫 출근룩", "en": "tailored blazer",
             "sub_queries": ["dress shirt", "straight trousers"], "category": None},
            {"ko": "데이트룩", "en": "romantic slip dress",
             "sub_queries": ["cropped cardigan", "strappy heels"], "category": None},
            {"ko": "여름 페스티벌룩", "en": "graphic crop top",
             "sub_queries": ["denim shorts", "bucket hat"], "category": None},
            {"ko": "겨울 여행룩", "en": "warm padded coat",
             "sub_queries": ["chunky knit sweater", "wool beanie"], "category": None},
            {"ko": "운동 갈 때 입을 옷", "en": "athletic tank top",
             "sub_queries": ["training shorts", "running shoes"], "category": None},
            {"ko": "면접룩", "en": "tailored blazer",
             "sub_queries": ["white dress shirt", "tailored trousers"], "category": None},
            {"ko": "한여름에 시원한 옷", "en": "linen shirt",
             "sub_queries": ["cotton shorts", "breathable sundress"], "category": None},
            {"ko": "캠퍼스룩", "en": "oversized sweatshirt",
             "sub_queries": ["wide jeans", "canvas sneakers"], "category": None},
            {"ko": "장마철에 입을 옷", "en": "waterproof trench coat",
             "sub_queries": ["ankle rain boots", "nylon crossbody bag"], "category": None},
            {"ko": "명절에 입을 단정한 옷", "en": "neat knit cardigan",
             "sub_queries": ["pleated midi skirt", "modest blouse"], "category": None},
        ],
    },
]


PATTERNS_MEN: list[dict] = [
    {
        "id": "p1_color_category",
        "name_ko": "[컬러] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "버건디 가디건", "en": "burgundy cardigan", "category": "knitwear"},
            {"ko": "카키 셔츠", "en": "khaki shirt", "category": "tops"},
            {"ko": "네이비 블레이저", "en": "navy blazer", "category": "outerwear"},
            {"ko": "베이지 트렌치코트", "en": "beige trench coat", "category": "outerwear"},
            {"ko": "블랙 터틀넥", "en": "black turtleneck", "category": "knitwear"},
            {"ko": "흰색 스니커즈", "en": "white sneakers", "category": "sneakers"},
            {"ko": "차콜 슬랙스", "en": "charcoal slacks", "category": "bottoms"},
            {"ko": "브라운 로퍼", "en": "brown loafers", "category": "shoes"},
            {"ko": "올리브 카고 팬츠", "en": "olive cargo pants", "category": "bottoms"},
            {"ko": "아이보리 옥스포드 셔츠", "en": "ivory oxford shirt", "category": "tops"},
            {"ko": "레드 니트 베스트", "en": "red knit vest", "category": "knitwear"},
            {"ko": "연청 데님 자켓", "en": "light blue denim jacket", "category": "outerwear"},
            {"ko": "라벤더 후드티", "en": "lavender hoodie", "category": "tops"},
            {"ko": "머스터드 스웨터", "en": "mustard sweater", "category": "knitwear"},
            {"ko": "그레이 트라우저", "en": "grey trousers", "category": "bottoms"},
            {"ko": "핑크 옥스포드 셔츠", "en": "pink oxford shirt", "category": "tops"},
            {"ko": "블랙 메신저백", "en": "black messenger bag", "category": "bags"},
            {"ko": "다크그린 코트", "en": "dark green coat", "category": "outerwear"},
            {"ko": "오렌지 티셔츠", "en": "orange t-shirt", "category": "tops"},
            {"ko": "코발트블루 스웨터", "en": "cobalt blue sweater", "category": "knitwear"},
        ],
    },
    {
        "id": "p2_material_category",
        "name_ko": "[소재] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "레더 자켓", "en": "leather jacket", "category": "outerwear"},
            {"ko": "울 코트", "en": "wool coat", "category": "outerwear"},
            {"ko": "코듀로이 팬츠", "en": "corduroy pants", "category": "bottoms"},
            {"ko": "생지 데님", "en": "raw denim jeans", "category": "bottoms"},
            {"ko": "캐시미어 니트", "en": "cashmere knit sweater", "category": "knitwear"},
            {"ko": "린넨 셔츠", "en": "linen shirt", "category": "tops"},
            {"ko": "스웨이드 부츠", "en": "suede boots", "category": "shoes"},
            {"ko": "트위드 자켓", "en": "tweed jacket", "category": "outerwear"},
            {"ko": "벨벳 블레이저", "en": "velvet blazer", "category": "outerwear"},
            {"ko": "새틴 바시티 자켓", "en": "satin varsity jacket", "category": "outerwear"},
            {"ko": "모헤어 가디건", "en": "mohair cardigan", "category": "knitwear"},
            {"ko": "코튼 후드집업", "en": "cotton zip-up hoodie", "category": "tops"},
            {"ko": "실크 캠프칼라 셔츠", "en": "silk camp collar shirt", "category": "tops"},
            {"ko": "나일론 바람막이", "en": "nylon windbreaker", "category": "outerwear"},
            {"ko": "무스탕 자켓", "en": "shearling jacket", "category": "outerwear"},
            {"ko": "골지 니트 탑", "en": "ribbed knit top", "category": "tops"},
            {"ko": "메시 저지 탑", "en": "mesh jersey top", "category": "tops"},
            {"ko": "캔버스 토트백", "en": "canvas tote bag", "category": "bags"},
            {"ko": "플리스 집업", "en": "fleece zip-up jacket", "category": "outerwear"},
            {"ko": "니트 폴로", "en": "knit polo shirt", "category": "knitwear"},
        ],
    },
    {
        "id": "p3_fit_category",
        "name_ko": "[핏/실루엣] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "오버사이즈 셔츠", "en": "oversized shirt", "category": "tops"},
            {"ko": "크롭 워크자켓", "en": "cropped work jacket", "category": "outerwear"},
            {"ko": "와이드 팬츠", "en": "wide-leg pants", "category": "bottoms"},
            {"ko": "슬림 터틀넥", "en": "slim fit turtleneck", "category": "knitwear"},
            {"ko": "박시한 티셔츠", "en": "boxy t-shirt", "category": "tops"},
            {"ko": "릴렉스핏 치노 쇼츠", "en": "relaxed chino shorts", "category": "bottoms"},
            {"ko": "스트레이트 진", "en": "straight leg jeans", "category": "bottoms"},
            {"ko": "릴렉스핏 블레이저", "en": "relaxed fit blazer", "category": "outerwear"},
            {"ko": "슬림핏 폴로 셔츠", "en": "slim fit polo shirt", "category": "tops"},
            {"ko": "배기 카고 팬츠", "en": "baggy cargo pants", "category": "bottoms"},
            {"ko": "하이웨이스트 슬랙스", "en": "high-waisted trousers", "category": "bottoms"},
            {"ko": "로우라이즈 진", "en": "low-rise jeans", "category": "bottoms"},
            {"ko": "롱 코트", "en": "longline coat", "category": "outerwear"},
            {"ko": "숏 패딩", "en": "cropped puffer jacket", "category": "outerwear"},
            {"ko": "플레어 팬츠", "en": "flared pants", "category": "bottoms"},
            {"ko": "투턱 와이드 슬랙스", "en": "pleated wide trousers", "category": "bottoms"},
            {"ko": "래글런 맨투맨", "en": "raglan sleeve sweatshirt", "category": "tops"},
            {"ko": "드롭숄더 맨투맨", "en": "drop shoulder sweatshirt", "category": "tops"},
            {"ko": "테이퍼드 슬랙스", "en": "tapered slacks", "category": "bottoms"},
            {"ko": "롱 파카", "en": "long parka", "category": "outerwear"},
        ],
    },
    {
        "id": "p4_mood_category",
        "name_ko": "[무드] + [카테고리]",
        "tier": "t2",
        "values": [
            {"ko": "그런지한 니트", "en": "grunge knit sweater", "category": "knitwear"},
            {"ko": "댄디한 테일러드 자켓", "en": "dandy tailored jacket", "category": "outerwear"},
            {"ko": "미니멀한 코트", "en": "minimal coat", "category": "outerwear"},
            {"ko": "빈티지 데님 자켓", "en": "vintage denim jacket", "category": "outerwear"},
            {"ko": "레트로 맨투맨", "en": "retro sweatshirt", "category": "tops"},
            {"ko": "프레피 가디건", "en": "preppy cardigan", "category": "knitwear"},
            {"ko": "엣지있는 레더 자켓", "en": "edgy leather jacket", "category": "outerwear"},
            {"ko": "러기드 워크웨어 자켓", "en": "rugged workwear jacket", "category": "outerwear"},
            {"ko": "클린한 옥스포드 셔츠", "en": "clean-cut oxford shirt", "category": "tops"},
            {"ko": "시크한 블랙 터틀넥", "en": "sleek black turtleneck", "category": "knitwear"},
            {"ko": "포근한 니트", "en": "cozy knit sweater", "category": "knitwear"},
            {"ko": "스포티한 바람막이", "en": "sporty windbreaker", "category": "outerwear"},
            {"ko": "단정한 울 슬랙스", "en": "refined wool slacks", "category": "bottoms"},
            {"ko": "스트릿 후드티", "en": "streetwear hoodie", "category": "tops"},
            {"ko": "보헤미안 패턴 셔츠", "en": "bohemian patterned shirt", "category": "tops"},
            {"ko": "펑크 부츠", "en": "punk boots", "category": "shoes"},
            {"ko": "클래식 트렌치코트", "en": "classic trench coat", "category": "outerwear"},
            {"ko": "모던한 블레이저", "en": "modern tailored blazer", "category": "outerwear"},
            {"ko": "유니크한 그래픽 니트", "en": "quirky graphic knit sweater", "category": "knitwear"},
            {"ko": "유틸리티 자켓", "en": "utility jacket", "category": "outerwear"},
        ],
    },
    {
        "id": "p5_aesthetic",
        "name_ko": "[에스테틱/씬 키워드] + [아이템]",
        "tier": "t2",
        "values": [
            {"ko": "Y2K 배기 진", "en": "y2k baggy jeans", "category": "bottoms"},
            {"ko": "고프코어 자켓", "en": "gorpcore jacket", "category": "outerwear"},
            {"ko": "다크아카데미아 블레이저", "en": "dark academia blazer", "category": "outerwear"},
            {"ko": "아이비리그 옥스포드 셔츠", "en": "ivy league oxford shirt", "category": "tops"},
            {"ko": "스케이트 배기 팬츠", "en": "skate baggy pants", "category": "bottoms"},
            {"ko": "시티보이 팬츠", "en": "city boy style pants", "category": "bottoms"},
            {"ko": "놈코어 티셔츠", "en": "normcore t-shirt", "category": "tops"},
            {"ko": "피셔맨 스웨터", "en": "heritage fisherman sweater", "category": "knitwear"},
            {"ko": "테크웨어 팬츠", "en": "techwear pants", "category": "bottoms"},
            {"ko": "인디슬리즈 티", "en": "indie sleaze tee", "category": "tops"},
            {"ko": "올드머니 니트", "en": "old money knit sweater", "category": "knitwear"},
            {"ko": "아방가르드 코트", "en": "avant-garde coat", "category": "outerwear"},
            {"ko": "아메카지 셔츠", "en": "amekaji japanese workwear shirt", "category": "tops"},
            {"ko": "애슬레저 조거", "en": "athleisure joggers", "category": "bottoms"},
            {"ko": "밀리터리 자켓", "en": "military jacket", "category": "outerwear"},
            {"ko": "웨스턴 부츠", "en": "western boots", "category": "shoes"},
            {"ko": "모드룩 해링턴 자켓", "en": "mod harrington jacket", "category": "outerwear"},
            {"ko": "프렌치 워크 자켓", "en": "french chore coat", "category": "outerwear"},
            {"ko": "그런지 플란넬 셔츠", "en": "grunge flannel shirt", "category": "tops"},
            {"ko": "인디 밴드 티", "en": "indie band graphic tee", "category": "tops"},
        ],
    },
    {
        "id": "p6_pattern_detail",
        "name_ko": "[패턴/디테일] + [카테고리]",
        "tier": "t1",
        "values": [
            {"ko": "스트라이프 셔츠", "en": "striped shirt", "category": "tops"},
            {"ko": "체크 자켓", "en": "checked jacket", "category": "outerwear"},
            {"ko": "케이블 니트", "en": "cable knit sweater", "category": "knitwear"},
            {"ko": "아가일 베스트", "en": "argyle knit vest", "category": "knitwear"},
            {"ko": "플로럴 캠프 셔츠", "en": "floral print camp shirt", "category": "tops"},
            {"ko": "도트 셔츠", "en": "polka dot shirt", "category": "tops"},
            {"ko": "하운드투스 코트", "en": "houndstooth coat", "category": "outerwear"},
            {"ko": "레오파드 가디건", "en": "leopard print cardigan", "category": "knitwear"},
            {"ko": "플란넬 체크 오버셔츠", "en": "plaid flannel overshirt", "category": "tops"},
            {"ko": "그래픽 티셔츠", "en": "graphic print t-shirt", "category": "tops"},
            {"ko": "자수 셔츠", "en": "embroidered shirt", "category": "tops"},
            {"ko": "퀼팅 자켓", "en": "quilted jacket", "category": "outerwear"},
            {"ko": "페어아일 스웨터", "en": "fair isle sweater", "category": "knitwear"},
            {"ko": "크로셰 니트 베스트", "en": "crochet knit vest", "category": "knitwear"},
            {"ko": "패치워크 셔츠", "en": "patchwork shirt", "category": "tops"},
            {"ko": "핀스트라이프 슬랙스", "en": "pinstripe trousers", "category": "bottoms"},
            {"ko": "타이다이 티셔츠", "en": "tie-dye t-shirt", "category": "tops"},
            {"ko": "컬러블록 니트", "en": "colorblock knit sweater", "category": "knitwear"},
            {"ko": "카고 포켓 팬츠", "en": "cargo pocket pants", "category": "bottoms"},
            {"ko": "수베니어 자켓", "en": "embroidered souvenir jacket", "category": "outerwear"},
        ],
    },
    {
        "id": "p7_occasion",
        "name_ko": "[상황/TPO] + [아이템] — 대조군",
        "tier": "t3",
        "values": [
            {"ko": "소개팅 셔츠", "en": "first date shirt", "category": "tops"},
            {"ko": "출근용 블레이저", "en": "office workwear blazer", "category": "outerwear"},
            {"ko": "하객룩 수트 자켓", "en": "wedding guest suit jacket", "category": "outerwear"},
            {"ko": "휴양지 셔츠", "en": "vacation resort shirt", "category": "tops"},
            {"ko": "페스티벌 탑", "en": "music festival top", "category": "tops"},
            {"ko": "면접용 슬랙스", "en": "job interview trousers", "category": "bottoms"},
            {"ko": "데일리 니트", "en": "everyday casual knit", "category": "knitwear"},
            {"ko": "여행용 백", "en": "travel bag", "category": "bags"},
            {"ko": "운동할 때 입을 탑", "en": "workout top", "category": "activewear"},
            {"ko": "집에서 입는 라운지웨어", "en": "loungewear set", "category": "tops"},
            {"ko": "졸업식 자켓", "en": "graduation ceremony jacket", "category": "outerwear"},
            {"ko": "캠핑 자켓", "en": "camping outdoor jacket", "category": "outerwear"},
            {"ko": "클럽 파티 탑", "en": "party night out top", "category": "tops"},
            {"ko": "장마철 아우터", "en": "rainy season outer jacket", "category": "outerwear"},
            {"ko": "한여름 셔츠", "en": "hot summer breathable shirt", "category": "tops"},
            {"ko": "한겨울 코트", "en": "warm winter coat", "category": "outerwear"},
            {"ko": "환절기 가디건", "en": "light layering cardigan", "category": "knitwear"},
            {"ko": "피크닉 쇼츠", "en": "picnic day shorts", "category": "bottoms"},
            {"ko": "공연 보러 갈 때 자켓", "en": "concert outfit jacket", "category": "outerwear"},
            {"ko": "주말 브런치 셔츠", "en": "weekend brunch shirt", "category": "tops"},
        ],
    },
]
